In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('realtor-data.csv')
df

,status,price,bed,bath,acre_lot,full_address,street,city,state,zip_code,house_size,sold_date
0,for_sale,105000.0,3.0,2.0,0.12,"Sector Yahuecas Titulo # V84, Adjuntas, PR, 00601",Sector Yahuecas Titulo # V84,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,for_sale,80000.0,4.0,2.0,0.08,"Km 78 9 Carr # 135, Adjuntas, PR, 00601",Km 78 9 Carr # 135,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,for_sale,67000.0,2.0,1.0,0.15,"556G 556-G 16 St, Juana Diaz, PR, 00795",556G 556-G 16 St,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,for_sale,145000.0,4.0,2.0,0.10,"R5 Comunidad El Paraso Calle De Oro R-5 Ponce,...",R5 Comunidad El Paraso Calle De Oro R-5 Ponce,Ponce,Puerto Rico,731.0,1800.0,NaN
4,for_sale,65000.0,6.0,2.0,0.05,"14 Navarro, Mayaguez, PR, 00680",14 Navarro,Mayaguez,Puerto Rico,680.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
923154,for_sale,445000.0,1.0,2.0,0.99,"1008 King St, Chappaqua, NY, 10514",1008 King St,Chappaqua,New York,10514.0,1052.0,2011-05-09
923155,for_sale,418000.0,4.0,2.0,0.40,"3 Elmwood Dr, Monroe, NY, 10950",3 Elmwood Dr,Monroe,New York,10950.0,1650.0,2015-07-21
923156,for_sale,469000.0,4.0,2.0,0.18,"13 N Conger Ave, Congers, NY, 10920",13 N Conger Ave,Congers,New York,10920.0,2123.0,NaN
923157,for_sale,825000.0,5.0,5.0,0.79,"7 Miller Rd, Valley Cottage, NY, 10989",7 Miller Rd,Valley Cottage,New York,10989.0,3775.0,2010-06-02
923158,for_sale,88000.0,NaN,NaN,35.00,"D18 Half Moon Bay Dr, Croton On Hudson, NY, 10520",D18 Half Moon Bay Dr,Croton On Hudson,New York,10520.0,780.0,NaN

In [3]:
df.columns

Index(['status', 'price', 'bed', 'bath', 'acre_lot', 'full_address', 'street',
       'city', 'state', 'zip_code', 'house_size', 'sold_date'],
      dtype='object')

### EDA

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923159 entries, 0 to 923158
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   status        923159 non-null  object
 1   price         923088 non-null  float64
 2   bed           791456 non-null  float64
 3   bath          807967 non-null  float64
 4   acre_lot      649536 non-null  float64
 5   full_address  923159 non-null  object
 6   street        921021 non-null  object
 7   city          923085 non-null  object
 8   state         923159 non-null  object
 9   zip_code      922954 non-null  float64
 10  house_size    625316 non-null  float64
 11  sold_date     456396 non-null  object
dtypes: float64(6), object(6)
memory usage: 84.5+ MB

In [5]:
df.describe()

,price,bed,bath,acre_lot,zip_code,house_size
count,9.230880e+05,791456.000000,807967.000000,649536.000000,922954.000000,6.253160e+05
mean,8.841225e+05,3.330352,2.488164,17.075888,6590.061523,2.141644e+03
std,2.623745e+06,2.070402,1.940057,962.322866,3818.208203,3.035327e+03
min,0.000000e+00,1.000000,1.000000,0.000000,601.000000,1.000000e+02
25%,2.690000e+05,2.000000,1.000000,0.110000,2919.000000,1.130000e+03
50%,4.750000e+05,3.000000,2.000000,0.290000,7004.000000,1.651000e+03
75%,8.399000e+05,4.000000,3.000000,1.150000,10001.000000,2.499000e+03
max,8.750000e+08,123.000000,198.000000,100000.000000,99999.000000,1.450112e+06

In [6]:
df.isna().sum()

status               0
price               71
bed             131703
bath            115192
acre_lot        273623
full_address         0
street            2138
city                74
state                0
zip_code           205
house_size      297843
sold_date       466763
dtype: int64

### Handling Null values

In [7]:
x = [i for i in df.columns if df[f"{i}"].isna().sum()>=1]
print("Percentage of NULL Values: ")
for i in x:
    print(i,": {:.2f}".format((df[f"{i}"].isna().sum()*100/len(df))), "%")

Percentage of NULL Values:
price : 0.01 %
bed : 14.27 %
bath : 12.48 %
acre_lot : 29.64 %
street : 0.23 %
city : 0.01 %
zip_code : 0.02 %
house_size : 32.26 %
sold_date : 50.56 %

In [8]:
df1 = df.drop("sold_date", axis = 1)
df1

,status,price,bed,bath,acre_lot,full_address,street,city,state,zip_code,house_size
0,for_sale,105000.0,3.0,2.0,0.12,"Sector Yahuecas Titulo # V84, Adjuntas, PR, 00601",Sector Yahuecas Titulo # V84,Adjuntas,Puerto Rico,601.0,920.0
1,for_sale,80000.0,4.0,2.0,0.08,"Km 78 9 Carr # 135, Adjuntas, PR, 00601",Km 78 9 Carr # 135,Adjuntas,Puerto Rico,601.0,1527.0
2,for_sale,67000.0,2.0,1.0,0.15,"556G 556-G 16 St, Juana Diaz, PR, 00795",556G 556-G 16 St,Juana Diaz,Puerto Rico,795.0,748.0
3,for_sale,145000.0,4.0,2.0,0.10,"R5 Comunidad El Paraso Calle De Oro R-5 Ponce,...",R5 Comunidad El Paraso Calle De Oro R-5 Ponce,Ponce,Puerto Rico,731.0,1800.0
4,for_sale,65000.0,6.0,2.0,0.05,"14 Navarro, Mayaguez, PR, 00680",14 Navarro,Mayaguez,Puerto Rico,680.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
923154,for_sale,445000.0,1.0,2.0,0.99,"1008 King St, Chappaqua, NY, 10514",1008 King St,Chappaqua,New York,10514.0,1052.0
923155,for_sale,418000.0,4.0,2.0,0.40,"3 Elmwood Dr, Monroe, NY, 10950",3 Elmwood Dr,Monroe,New York,10950.0,1650.0
923156,for_sale,469000.0,4.0,2.0,0.18,"13 N Conger Ave, Congers, NY, 10920",13 N Conger Ave,Congers,New York,10920.0,2123.0
923157,for_sale,825000.0,5.0,5.0,0.79,"7 Miller Rd, Valley Cottage, NY, 10989",7 Miller Rd,Valley Cottage,New York,10989.0,3775.0
923158,for_sale,88000.0,NaN,NaN,35.00,"D18 Half Moon Bay Dr, Croton On Hudson, NY, 10520",D18 Half Moon Bay Dr,Croton On Hudson,New York,10520.0,780.0

In [9]:
df1['price'] = df1.price.fillna(df1.price.mean())
df1

,status,price,bed,bath,acre_lot,full_address,street,city,state,zip_code,house_size
0,for_sale,105000.0,3.0,2.0,0.12,"Sector Yahuecas Titulo # V84, Adjuntas, PR, 00601",Sector Yahuecas Titulo # V84,Adjuntas,Puerto Rico,601.0,920.0
1,for_sale,80000.0,4.0,2.0,0.08,"Km 78 9 Carr # 135, Adjuntas, PR, 00601",Km 78 9 Carr # 135,Adjuntas,Puerto Rico,601.0,1527.0
2,for_sale,67000.0,2.0,1.0,0.15,"556G 556-G 16 St, Juana Diaz, PR, 00795",556G 556-G 16 St,Juana Diaz,Puerto Rico,795.0,748.0
3,for_sale,145000.0,4.0,2.0,0.10,"R5 Comunidad El Paraso Calle De Oro R-5 Ponce,...",R5 Comunidad El Paraso Calle De Oro R-5 Ponce,Ponce,Puerto Rico,731.0,1800.0
4,for_sale,65000.0,6.0,2.0,0.05,"14 Navarro, Mayaguez, PR, 00680",14 Navarro,Mayaguez,Puerto Rico,680.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
923154,for_sale,445000.0,1.0,2.0,0.99,"1008 King St, Chappaqua, NY, 10514",1008 King St,Chappaqua,New York,10514.0,1052.0
923155,for_sale,418000.0,4.0,2.0,0.40,"3 Elmwood Dr, Monroe, NY, 10950",3 Elmwood Dr,Monroe,New York,10950.0,1650.0
923156,for_sale,469000.0,4.0,2.0,0.18,"13 N Conger Ave, Congers, NY, 10920",13 N Conger Ave,Congers,New York,10920.0,2123.0
923157,for_sale,825000.0,5.0,5.0,0.79,"7 Miller Rd, Valley Cottage, NY, 10989",7 Miller Rd,Valley Cottage,New York,10989.0,3775.0
923158,for_sale,88000.0,NaN,NaN,35.00,"D18 Half Moon Bay Dr, Croton On Hudson, NY, 10520",D18 Half Moon Bay Dr,Croton On Hudson,New York,10520.0,780.0

In [10]:
df1.isna().sum()

status               0
price                0
bed             131703
bath            115192
acre_lot        273623
full_address         0
street            2138
city                74
state                0
zip_code           205
house_size      297843
dtype: int64

In [20]:
df1.describe()

,price,bed,bath,acre_lot,zip_code,house_size
count,9.231590e+05,791456.000000,807967.000000,649536.000000,922954.000000,6.253160e+05
mean,8.841225e+05,3.330352,2.488164,17.075888,6590.061523,2.141644e+03
std,2.623644e+06,2.070402,1.940057,962.322866,3818.208203,3.035327e+03
min,0.000000e+00,1.000000,1.000000,0.000000,601.000000,1.000000e+02
25%,2.690000e+05,2.000000,1.000000,0.110000,2919.000000,1.130000e+03
50%,4.750000e+05,3.000000,2.000000,0.290000,7004.000000,1.651000e+03
75%,8.399000e+05,4.000000,3.000000,1.150000,10001.000000,2.499000e+03
max,8.750000e+08,123.000000,198.000000,100000.000000,99999.000000,1.450112e+06

In [24]:
bed_city = {}

for city in df1['city'].unique():
    bed_city[f"{city}"] = 0
    bed_city[f"{city}"] = df1[df1["city"] == city]['bed'].median()

In [25]:
bed_city

{'Adjuntas': 3.0,
 'Juana Diaz': 3.0,
 'Ponce': 3.0,
 'Mayaguez': 4.0,
 'San Sebastian': 3.0,
 'Ciales': 3.0,
 'Las Marias': 5.0,
 'Isabela': 3.0,
 'Lares': 3.0,
 'Utuado': 3.0,
 'Yauco': 3.0,
 'Anasco': 6.0,
 'Moca': 3.0,
 'Coamo': 3.0,
 'Guayanilla': 3.5,
 'Manati': 3.0,
 'Villalba': 6.0,
 'Santa Isabel': 3.0,
 'Penuelas': 3.0,
 'Hatillo': 4.0,
 'Aguada': 3.0,
 'Rincon': 3.0,
 'Aguadilla': 4.0,
 'Maricao': 5.0,
 'Hormigueros': 4.0,
 'Guanica': 3.0,
 'Cabo Rojo': 3.0,
 'San German': 3.0,
 'Lajas': 4.0,
 'Arecibo': 3.0,
 'Camuy': 3.0,
 'Morovis': 5.0,
 'Barceloneta': 3.0,
 'Quebradillas': 5.0,
 'Vega Baja': 3.0,
 'Caguas': 3.0,
 'Dorado': 3.0,
 'Toa Baja': 3.0,
 'Toa Alta': 3.0,
 'Vega Alta': 3.0,
 'Corozal': 3.0,
 'Naranjito': 3.0,
 'Boqueron': nan,
 'Carolina': 3.0,
 'Sabana Grande': 3.0,
 'Canovanas': 3.0,
 'Jayuya': 3.0,
 'Trujillo Alto': 3.0,
 'Florida': 3.0,
 'Las Piedras': 3.0,
 'Juncos': 3.0,
 'Orocovis': 4.0,
 'Barranquitas': 3.0,
 'Fajardo': 3.0,
 'Comerio': 3.0,
 'ManatÃ­': nan,
 'Aibonito': 4.5,
 'Sabana Hoyos': 3.0,
 'Catano': 3.0,
 'San Juan': 3.0,
 'Guaynabo': 4.0,
 'Guayama': 3.0,
 'Gurabo': 3.0,
 'Aguas Buenas': 4.0,
 'San Lorenzo': 3.0,
 'Bayamon': 3.0,
 'Cayey': 3.0,
 'Cidra': 3.0,
 'Arroyo': 4.0,
 'Patillas': 3.0,
 'Loiza': 3.0,
 'Maunabo': 3.0,
 'Humacao': 3.0,
 'Yabucoa': 3.0,
 'Naguabo': 3.0,
 'Salinas': 3.0,
 'BayamÃ³n': 5.0,
 'Old San Juan': 3.0,
 'Rio Grande': 3.0,
 'Ceiba': 3.0,
 'Santurce': 2.0,
 'Luquillo': 3.0,
 'Vieques': 3.0,
 'Culebra': 5.0,
 'Saint Thomas': 4.0,
 'Saint John': 4.0,
 'Christiansted': 3.0,
 'Frederiksted': 4.0,
 'Kingshill': 3.0,
 'nan': nan,
 'Isla Verde': 1.0,
 'Hato Rey': 4.0,
 'Condado': 2.0,
 'Rio Piedras': 3.0,
 'Agawam': 3.0,
 'Pelham': 3.0,
 'Amherst': 4.0,
 'Conway': 3.0,
 'Buckland': 3.0,
 'Granby': 3.0,
 'Greenfield': 3.0,
 'Northampton': 3.0,
 'Montague': 3.0,
 'Springfield': 4.0,
 'Whately': 3.0,
 'Sunderland': 4.0,
 'Chicopee': 3.0,
 'Belchertown': 3.0,
 'South Hadley': 3.0,
 'Hadley': 4.0,
 'Ludlow': 3.0,
 'Easthampton': 3.0,
 'Orange': 3.0,
 'Holyoke': 4.0,
 'Southampton': 3.0,
 'Barre': 4.0,
 'Shutesbury': 3.0,
 'Goshen': 4.0,
 'Hatfield': 3.0,
 'Deerfield': 4.0,
 'Westhampton': 3.0,
 'Erving': 3.0,
 'Athol': 4.0,
 'Wendell': nan,
 'Williamsburg': 3.0,
 'New Salem': 3.0,
 'Ware': 4.0,
 'Gill': 4.0,
 'Leverett': 2.0,
 'Ashfield': 3.0,
 'Westfield': 4.0,
 'West Springfield': 3.0,
 'Shelburne': 3.0,
 'Chesterfield': 3.5,
 'Blandford': 4.0,
 'Willington': 3.0,
 'Coventry': 3.0,
 'East Windsor': 3.0,
 'Vernon': 3.0,
 'Manchester': 3.0,
 'South Windsor': 3.0,
 'Ellington': 3.0,
 'Longmeadow': 4.0,
 'Monson': 3.0,
 'Northbridge': 3.0,
 'Stafford': 3.0,
 'Enfield': 3.0,
 'Templeton': 3.0,
 'Palmer': 4.0,
 'Brimfield': 3.0,
 'Chester': 3.0,
 'Cummington': 1.0,
 'Granville': 3.0,
 'Worthington': 4.0,
 'Becket': 3.0,
 'Otis': 3.0,
 'Savoy': 5.0,
 'Southwick': 3.0,
 'Windsor Locks': 3.0,
 'East Longmeadow': 3.0,
 'Hardwick': 3.0,
 'West Brookfield': 3.0,
 'North Adams': 4.0,
 'Adams': 3.0,
 'Huntington': 4.0,
 'Phillipston': 6.0,
 'Andover': 4.0,
 'Warren': 3.0,
 'Fitzwilliam': 3.0,
 'Tolland': 3.0,
 'Bolton': 3.0,
 'Somers': 3.0,
 'Wilbraham': 4.0,
 'Hebron': 3.0,
 'Hampden': 3.0,
 'Wales': 2.0,
 'New Braintree': 3.0,
 'Marlborough': 3.0,
 'Russell': 6.0,
 'Plainfield': 4.0,
 'Windsor': 3.0,
 'Hinsdale': 3.0,
 'Readsboro': 2.0,
 'Washington': 3.0,
 'Charlemont': nan,
 'Cheshire': 4.0,
 'Middlefield': 3.0,
 'Dalton': 3.0,
 'Monroe': 2.0,
 'Peru': 3.0,
 'Pittsfield': 4.0,
 'Williamstown': 3.0,
 'Clarksburg': 3.0,
 'Barkhamsted': 3.0,
 'Lanesborough': 3.0,
 'Hubbardston': 3.0,
 'Sheffield': 3.0,
 'Sandisfield': 3.0,
 'Winchester': 3.0,
 'East Granby': 3.0,
 'New Marlborough': 4.0,
 'Monterey': 3.0,
 'Suffield': 4.0,
 'Great Barrington': 4.0,
 'Norfolk': 3.0,
 'Tyringham': 2.0,
 'New Ashford': 4.0,
 'North Canaan': 3.0,
 'Colebrook': 3.0,
 'New Marlboro': 11.0,
 'Lee': 4.0,
 'Simsbury': 4.0,
 'Stockbridge': 3.0,
 'Canaan': 3.0,
 'Canton': 4.0,
 'Hawley': 3.5,
 'Montgomery': 3.0,
 'Princeton': 4.0,
 'Oakham': 3.0,
 'Petersham': nan,
 'North Brookfield': 3.0,
 'Westminster': 3.0,
 'Rutland': 3.0,
 'Plainville': 3.0,
 'Avon': 4.0,
 'Farmington': 3.0,
 'New Hartford': 3.0,
 'Bloomfield': 3.0,
 'Hancock': 3.0,
 'Burlington': 3.0,
 'Bristol': 3.0,
 'Whitingham': 4.0,
 'Berlin': 3.0,
 'Rowe': nan,
 'Southington': 3.0,
 'Mansfield': 3.0,
 'Northfield': 3.0,
 'Columbia': 3.0,
 'Royalston': 4.0,
 'East Hampton': 3.0,
 'East Hartford': 3.0,
 'Storrs': 2.0,
 'Glastonbury': 4.0,
 'Richmond': 3.0,
 'Stafford Springs': 2.0,
 'Holland': 2.0,
 'Troy': 3.0,
 'Union': 3.0,
 'Warwick': 3.0,
 'East Brookfield': 2.0,
 'Auburn': 3.0,
 'Bernardston': 5.0,
 'Guilford': 3.0,
 'Colrain': 4.0,
 'Leyden': nan,
 'Stamford': 3.0,
 'Pownal': 3.0,
 'Lenox': 3.0,
 'Spencer': 3.0,
 'Charlton': 3.0,
 'Sutton': 3.0,
 'Gardner': 3.0,
 'Millbury': 3.0,
 'Leicester': 4.0,
 'Paxton': 3.0,
 'Worcester': 4.0,
 'Sturbridge': 3.0,
 'Oxford': 3.0,
 'Brookfield': 3.0,
 'Holden': 3.0,
 'McCormick': nan,
 'West Boylston': 3.0,
 'Grafton': 3.0,
 'Shrewsbury': 4.0,
 'Ashburnham': 3.0,
 'Halifax': 3.0,
 'Southbridge': 4.0,
 'Eastford': 2.0,
 'Ashford': 3.0,
 'Torrington': 3.0,
 'Brooklyn': 3.0,
 'Woodstock': 3.0,
 'Dudley': 3.0,
 'Chaplin': 3.5,
 'Pomfret': 3.0,
 'Thompson': 3.0,
 'Hampton': 3.0,
 'Woodford': 2.0,
 'Searsburg': 2.5,
 'Bennington': 3.0,
 'Putnam': 3.0,
 'Webster': 3.0,
 'Killingly': 3.0,
 'Winchendon': 3.0,
 'Harwinton': 3.0,
 'West Hartford': 3.0,
 'Hartford': 4.0,
 'Windham': 3.0,
 'Lebanon': 3.0,
 'East Haddam': 3.0,
 'Durham': 3.0,
 'Wethersfield': 3.0,
 'New Britain': 4.0,
 'Newington': 3.0,
 'Middletown': 3.0,
 'Claverack': 3.0,
 'Copake': 4.0,
 'Hillsdale': 4.0,
 'Millerton': 3.0,
 'Salisbury': 3.0,
 'Sharon': 3.0,
 'West Stockbridge': 3.0,
 'Alford': 3.0,
 'Austerlitz': 3.0,
 'Egremont': 4.0,
 'Nassau': 3.0,
 'Hoosick Falls': 3.0,
 'East Chatham': 3.5,
 'Valatie': 3.0,
 'Watertown': 3.0,
 'Niverville': 3.0,
 'Kinderhook': 4.0,
 'Philmont': 4.5,
 'Bethlehem': 3.0,
 'Litchfield': 3.0,
 'Pittstown': 3.0,
 'Morris': 3.0,
 'Schodack Landing': 3.0,
 'New Lebanon': 4.0,
 'Thomaston': 3.0,
 'Taghkanic': 2.0,
 'Stephentown': 4.0,
 'Hoosick': 3.0,
 'Craryville': 4.0,
 'Mount Washington': 4.0,
 'Copake Falls': 3.0,
 'Sand Lake': 3.0,
 'Chatham': 4.0,
 'Cornwall': 4.0,
 'Petersburgh': 2.0,
 'Caroga': nan,
 'Ancram': 3.5,
 'East Nassau': 4.0,
 'Woodbury': 3.0,
 'Poestenkill': 3.0,
 'White Creek': 3.0,
 'Ghent': 3.0,
 'Chatham Village': 4.0,
 'Ancramdale': nan,
 'Nassau Village': nan,
 'Winhall': 4.0,
 'Northeast': 3.0,
 'Greenville': 3.0,
 'Spencertown': 5.0,
 'Brunswick': 3.0,
 'Middlebury': 3.0,
 'East Greenbush': 3.0,
 'Old Chatham': 4.0,
 'Hudson': 3.0,
 'Johnsonville': 3.0,
 'Wilmington': 3.0,
 'Colchester': 3.0,
 'Cromwell': 3.0,
 'Portland': 3.0,
 'Wallingford': 3.0,
 'Rocky Hill': 3.0,
 'Haddam': 3.0,
 'Meriden': 3.0,
 'North Branford': 3.0,
 'Marlboro': 4.0,
 'Madison': 3.0,
 'Elizaville': 3.0,
 'Wassaic': 5.0,
 'Kent': 3.0,
 'Millbrook': 4.0,
 'Amenia': 3.0,
 'Dover Plains': 3.0,
 'Clinton Corners': 3.0,
 'Red Hook': 4.0,
 'Stanfordville': 3.0,
 'Wingdale': 3.0,
 'Dover': 3.0,
 'Pine Plains': 3.0,
 'Gallatin': 3.0,
 'Milan': 2.0,
 'Stanford': 4.5,
 'Malden On Hudson': nan,
 'Salt Point': 3.0,
 'Brattleboro': 3.0,
 'Keene': 3.0,
 'Swanzey': 2.0,
 'Putney': 4.0,
 'Jaffrey': 3.0,
 'Westmoreland': 4.0,
 'Sullivan': 3.0,
 'Gilsum': 3.0,
 'Surry': 3.0,
 'Rindge': 3.0,
 'Dublin': 4.0,
 'Peterborough': 3.0,
 'Dummerston': 3.0,
 'Harrisville': nan,
 'Nelson': 3.0,
 'Newfane': 6.0,
 'Wardsboro': 4.0,
 'Fitchburg': 4.0,
 'Ashby': 3.0,
 'Ayer': 3.0,
 'Devens': 3.0,
 'Temple': 3.0,
 'Leominster': 3.0,
 'Billerica': 3.0,
 'Acton': 4.0,
 'Carlisle': 4.0,
 'Pepperell': 3.0,
 'Groton': 3.0,
 'Sterling': 3.0,
 'Lancaster': 3.0,
 'Harvard': 3.0,
 'Boxborough': 2.0,
 'Sudbury': 4.0,
 'Westford': 3.0,
 'Maynard': 3.0,
 'Lowell': 3.0,
 'Nashua': 3.0,
 'Shirley': 4.0,
 'Tyngsborough': 3.0,
 'Lunenburg': 3.0,
 'Boylston': 4.0,
 'Stow': 4.0,
 'Chelmsford': 3.0,
 'Clinton': 3.0,
 'Dracut': 3.0,
 'Hollis': 3.0,
 'Littleton': 3.0,
 'Dunstable': 3.0,
 'Concord': 3.0,
 'Northborough': 3.0,
 'Townsend': 3.0,
 'Tewksbury': 3.0,
 'New Ipswich': 3.0,
 'Mason': 3.0,
 'Brookline': 3.0,
 'Weston': 5.0,
 'Milford': 3.0,
 'Framingham': 3.0,
 'Westborough': 3.0,
 'Wellesley': 4.0,
 'Waltham': 3.0,
 'Wilton': 4.0,
 'Londonderry': 2.0,
 'Bedford': 4.0,
 'Weare': 3.0,
 'Hillsborough': 3.0,
 'Lyndeborough': 4.0,
 'Francestown': nan,
 'Antrim': 3.0,
 'Mont Vernon': 3.0,
 'Deering': 3.0,
 'New Boston': 3.0,
 'Southborough': 4.0,
 'Merrimack': 3.0,
 'Derry': 3.0,
 'Upton': 3.0,
 'Hopkinton': 3.0,
 'Uxbridge': 3.0,
 'Douglas': 3.0,
 'Wayland': 4.0,
 'Jefferson City': nan,
 'Ashland': 4.0,
 'Framington': 3.0,
 'Lincoln': 3.0,
 'Lexington': 5.0,
 'Woburn': 4.0,
 'Arlington': 3.0,
 'Natick': 4.0,
 'Methuen': 3.0,
 'Salem': 3.0,
 'Blackstone': 3.0,
 'Mendon': 3.0,
 'Burrillville': 3.0,
 'Woonsocket': 3.0,
 'North Smithfield': 3.0,
 'Millville': 3.0,
 'Chincoteague': nan,
 'Hopedale': 4.0,
 'Plaistow': 3.0,
 'Lyme': 3.0,
 'Scotland': 3.0,
 'Bozrah': 3.0,
 'Glocester': 3.0,
 'Providence': 4.0,
 'Cranston': 3.0,
 'East Providence': 3.0,
 'North Providence': 3.0,
 'North Attleboro': 3.0,
 'Johnston': 3.0,
 'North Kingstown': 3.0,
 'West Warwick': 3.0,
 'Millis': 2.0,
 'Attleboro': 3.0,
 'Pawtucket': 4.0,
 'Seekonk': 3.0,
 'Scituate': 2.0,
 'Cumberland': 3.0,
 'Franklin': 3.0,
 'Bellingham': 3.0,
 'Holliston': 3.0,
 'Medway': 4.0,
 'Sherborn': 4.0,
 'Wrentham': 2.0,
 'Barrington': 3.0,
 'Smithfield': 3.0,
 'West Greenwich': 3.0,
 'Foster': 3.0,
 'Central Falls': 5.5,
 'East Greenwich': 4.0,
 'Voluntown': 3.0,
 'Jamestown': 3.0,
 'Rehoboth': 3.0,
 'North Stonington': 3.0,
 'Exeter': 2.0,
 'Portsmouth': 3.0,
 'Foxboro': 4.0,
 'Medfield': 3.0,
 'South Kingstown': 3.0,
 'Stoneham': 3.0,
 'Newton': 4.0,
 'Malden': 4.0,
 'Somerville': 3.0,
 'Boston': 2.0,
 'Everett': 5.0,
 'Needham': 4.0,
 'Melrose': 3.0,
 'Lawrence': 4.0,
 'North Andover': 3.0,
 'Medford': 3.0,
 'Fenway': 1.0,
 'Saugus': 3.0,
 'Brighton': 4.0,
 'Charlestown': 3.0,
 'Back Bay': 2.0,
 'Norton': 3.0,
 'Walpole': 3.0,
 'Cambridge': 3.0,
 'Belmont': 3.0,
 'Wakefield': 3.0,
 'Reading': 3.0,
 'Allston': 1.0,
 'Jamaica Plain': 5.0,
 'Revere': 3.0,
 'Chelsea': 2.0,
 'North Reading': 3.0,
 'Lynnfield': 4.0,
 'Dedham': 3.0,
 'Roslindale': 4.0,
 'Middleton': 3.0,
 'Roxbury': 4.0,
 'Westwood': 3.0,
 'Georgetown': 3.0,
 'Boxford': 4.0,
 'Stoughton': 3.0,
 'Norwood': 3.0,
 'Milton': 3.0,
 'Haverhill': 3.0,
 'South Boston': 2.0,
 'East Boston': 2.0,
 'Seaport': 1.5,
 'Midtown': 2.0,
 'Dorchester': 4.0,
 'South End': 2.0,
 'Waterfront': 4.0,
 'Hyde Park': 3.0,
 'Peabody': 3.0,
 'Randolph': 4.0,
 'Easton': 4.0,
 'Groveland': 2.0,
 'Merrimac': 2.0,
 'Amesbury': 3.0,
 'Seabrook': 2.0,
 'Kingston': 3.0,
 'West Newbury': 3.5,
 'Hampstead': 3.0,
 'Brentwood': 2.0,
 'Rowley': 4.0,
 'East Kingston': nan,
 'Newbury': 3.0,
 'Atkinson': 2.0,
 'Ipswich': 3.0,
 'Beverly': 3.0,
 'Topsfield': 3.0,
 'Wenham': 4.0,
 'Danvers': 3.0,
 'Hamilton': 3.0,
 'Fremont': 2.0,
 'Stratham': 4.0,
 'Danville': 3.0,
 'Raymond': 3.0,
 'Sandown': 2.0,
 'South Hampton': 3.0,
 'Newburyport': 3.0,
 'Kensington': 4.0,
 'Epping': 2.0,
 'Lynn': 3.0,
 'Swampscott': 4.0,
 'Nahant': 3.0,
 'Weymouth': 2.0,
 'Braintree': 3.0,
 'Hingham': 3.0,
 'Holbrook': 3.0,
 'Essex': 3.0,
 'Gloucester': 3.0,
 'Quincy': 3.0,
 'Cohasset': 4.0,
 'Hull': 3.0,
 'Marshfield': 3.0,
 'Rockport': 2.0,
 'Marblehead': 3.0,
 'Winthrop': 3.0,
 'Norwell': 4.0,
 'Abington': 3.0,
 'Hanover': 4.0,
 'Rockland': 3.0,
 'North Hampton': 4.0,
 'Rye': 3.0,
 'Hampton Falls': 5.0,
 'West Bridgewater': 2.5,
 'Pembroke': 3.0,
 'Duxbury': 4.0,
 'Brockton': 3.0,
 'Whitman': 3.0,
 'Plymouth': 3.0,
 'Taunton': 3.0,
 'Raynham': 3.0,
 'East Bridgewater': 3.0,
 'Berkley': 4.0,
 'Bridgewater': 3.0,
 'Carver': 3.0,
 'Freetown': 3.0,
 'Fall River': 4.0,
 'Lakeville': 2.0,
 'Middleboro': 3.0,
 'Dighton': 3.0,
 'Plympton': 4.0,
 'Hanson': 3.0,
 'Swansea': 3.0,
 'Somerset': 3.0,
 'New Bedford': 4.0,
 'Acushnet': 3.0,
 'Wareham': 3.0,
 'Rochester': 3.0,
 'Bourne': 3.0,
 'Marion': 4.0,
 'East Wareham': 3.0,
 'Onset': 3.0,
 'Buzzards Bay': 3.0,
 'Sagamore Beach': 3.0,
 'Pocasset': 3.0,
 'Mattapoisett': 3.0,
 'West Wareham': 3.0,
 'Monument Beach': 4.0,
 'Bournedale': 4.0,
 'Cataumet': 2.0,
 'Centerville': 3.0,
 'Sandwich': 3.0,
 'Barnstable': 3.0,
 'Falmouth': 3.0,
 'Hyannis': 3.0,
 'Marstons Mills': 3.0,
 'Mashpee': 3.0,
 'West Barnstable': 4.0,
 'East Falmouth': 3.0,
 'New Seabury': 3.0,
 'Chilmark': 5.0,
 'Aquinnah': 7.0,
 'Teaticket': 3.0,
 'East Sandwich': 3.0,
 'Edgartown': 4.0,
 'West Falmouth': 4.0,
 'Yarmouth': 3.0,
 'Woods Hole': 5.0,
 'Vineyard Haven': 4.0,
 'Fairhaven': 3.0,
 'Osterville': 3.0,
 'Oak Bluffs': 3.0,
 'Dartmouth': 4.0,
 'Nantucket': 4.0,
 'North Falmouth': 3.0,
 'Cotuit': 3.0,
 'Hyannis Port': 5.0,
 'Popponesset Island': 4.0,
 'West Tisbury': 4.0,
 'Siasconset': 6.0,
 'Popponesset': 3.0,
 'Forestdale': 4.0,
 'Tisbury': 9.0,
 'West Yarmouth': 2.0,
 'Cummaquid': 3.0,
 'Yarmouth Port': 3.0,
 'South Yarmouth': 3.0,
 'Brewster': 3.0,
 'West Chatham': 2.0,
 'South Dennis': 3.0,
 'Dennis': 3.0,
 'East Dennis': 4.0,
 'West Dennis': 4.0,
 'Dennis Port': 2.0,
 'North Chatham': 4.0,
 'Eastham': 2.0,
 'Harwich': 3.0,
 'Orleans': 3.0,
 'Wellfleet': 3.0,
 'Harwich Port': 4.0,
 'North Eastham': 3.0,
 'South Chatham': 3.0,
 'East Harwich': 3.0,
 'West Harwich': 3.0,
 'North Truro': 2.0,
 'Provincetown': 2.0,
 'Truro': 4.0,
 'Westport': 4.0,
 'Tiverton': 3.0,
 'Little Compton': 3.0,
 'Newport': 3.0,
 'Cody': 3.0,
 'Narragansett': 3.0,
 'Block Island': 4.0,
 'Westerly': 3.0,
 'Stonington': 3.0,
 'Griswold': 3.0,
 'Ledyard': 3.0,
 'Preston': 3.0,
 'Mystic': 3.0,
 'Montauk': 3.0,
 'Southold': 3.0,
 'Norwich': 3.0,
 'Canterbury': 3.0,
 'Lisbon': 3.0,
 'Sprague': 3.0,
 'Goffstown': 3.0,
 'Hooksett': 3.0,
 'Candia': nan,
 'Loudon': 3.0,
 'Allenstown': 3.0,
 'Northwood': 3.0,
 'Nottingham': 3.0,
 'Stoddard': 2.0,
 'Henniker': 3.0,
 'Eliot': 3.0,
 'Newmarket': 3.0,
 'Dunbarton': 3.0,
 'Warner': 3.0,
 'Bow': 4.0,
 'Epsom': 3.0,
 'Chichester': 2.0,
 'Newfields': 2.5,
 'New Hampshire 03457': 4.0,
 'Marlow': 2.0,
 'Bradford': 5.0,
 'Madbury': 4.0,
 'Boscawen': 4.0,
 'Strafford': 1.0,
 'Gilmanton': 3.0,
 'Sanbornton': 4.0,
 'Barnstead': 3.0,
 'Tilton': 3.0,
 'Laconia': 3.0,
 'Campton': 3.0,
 'Hill': 3.0,
 'Gilford': 3.0,
 'Waterville Valley': 3.0,
 'Rumney': 4.0,
 'New Hampton': 3.0,
 'Meredith': 2.0,
 'Moultonborough': 2.0,
 'Alton': 3.0,
 'Alexandria': 3.0,
 'New Durham': 2.0,
 'Thornton': 3.0,
 'Tuftonboro': 3.0,
 'Wolfeboro': 4.0,
 'Ossipee': 3.0,
 'Danbury': 3.0,
 'New London': 3.0,
 'Grantham': 3.0,
 'Sunapee': 3.0,
 'Croydon': 2.0,
 'Wilmot': 3.0,
 'Tamworth': 3.0,
 'Holderness': 3.0,
 'Wentworth': 4.5,
 'Freedom': 3.0,
 'Effingham': 2.0,
 'Piermont': 3.0,
 'Benton': 4.0,
 'Cornish': 3.0,
 'Bartlett': 3.0,
 'Eaton': 12.0,
 'Albany': 3.0,
 'Jackson': 3.0,
 'Hales Location': 4.0,
 'Lyman': 4.0,
 'Sugar Hill': 4.0,
 'Bath': 3.0,
 'Acworth': 3.0,
 'Orford': 3.0,
 'Thetford': 4.0,
 'Claremont': 3.0,
 'Unity': 2.0,
 'Franconia': 3.0,
 'Wells River': 5.0,
 'Alstead': 4.0,
 'Fairlee': nan,
 'Langdon': 4.0,
 'Lempster': 3.0,
 'Topsham': 3.0,
 'West Fairlee': 3.0,
 'Ryegate': 3.0,
 'Corinth': 3.0,
 'Somersworth': 3.0,
 'Saco': 3.0,
 'Berwick': 3.0,
 'Rockingham': 4.0,
 'Weathersfield': 3.0,
 'Rollinsford': 4.0,
 'Athens': 2.0,
 'Carroll': 3.0,
 'Whitefield': 3.0,
 'Jefferson': 3.0,
 'Stewartstown': 3.0,
 'Errol': 3.0,
 'Millsfield': nan,
 'Clarksville': 2.0,
 'Bethel': 3.0,
 'Gorham': 4.0,
 'Dummer': 4.0,
 'Pittsburg': 3.0,
 'Newry': 6.0,
 'Northumberland': 3.0,
 'Stark': 4.0,
 'Lyndon': 3.0,
 'Waterford': 3.0,
 'Saint Johnsbury': 3.0,
 'Stratford': 3.0,
 'East Haven': 3.0,
 'Fryeburg': 3.0,
 'Lemington': 4.0,
 'Rangeley': 3.0,
 'Guildhall': nan,
 'Barnet': 4.0,
 'Kirby': 3.0,
 'Peacham': 8.0,
 'Walden': 3.0,
 'Victory': nan,
 'Newark': 5.0,
 'Warren Gore': 2.0,
 'Averill': nan,
 'Cabot': 3.0,
 'Wheelock': nan,
 'West Windsor': 4.0,
 'Hartland': 3.0,
 'Tunbridge': 3.0,
 'Cavendish': 3.0,
 'Baltimore': 2.0,
 'Vershire': nan,
 'Royalton': 4.0,
 'Townshend': 4.0,
 'Burke': 3.0,
 'Newfield': 3.0,
 'Parsonsfield': 6.0,
 'Brownfield': nan,
 'New Castle': 3.0,
 'Kittery': 3.0,
 'South Berwick': 4.0,
 'York': 3.0,
 'Bridgton': 3.0,
 'Sweden': 2.0,
 'Lovell': 7.0,
 'North Berwick': 3.0,
 'Waterboro': 3.0,
 'Sanford': 3.0,
 'Shapleigh': 3.0,
 'Limington': 3.0,
 'Wells': 3.0,
 'Ogunquit': 4.0,
 'Kennebunk': 4.0,
 'Hiram': 3.0,
 'Denmark': 3.0,
 'Limerick': 2.0,
 'Baldwin': 3.0,
 'Alfred': 4.0,
 'Springvale': nan,
 'Arundel': 3.0,
 'Van Buren': 3.0,
 'Harpswell': 3.0,
 'Cape Elizabeth': 4.0,
 'Phippsburg': 3.0,
 'Woolwich': 4.0,
 'Scarborough': 3.0,
 'West Bath': 2.0,
 'South Portland': 3.0,
 'Biddeford': 3.0,
 'Dayton': 4.0,
 'Old Orchard Beach': 3.0,
 'Westbrook': 3.0,
 'Bowdoinham': 3.0,
 'Gardiner': 3.0,
 'Monmouth': 3.0,
 'Hallowell': 3.0,
 'Pittston': 3.0,
 'Lewiston': 3.0,
 'Freeport': 4.0,
 'Augusta': 3.0,
 'West Gardiner': 3.0,
 'Standish': 3.0,
 'Sebago': 3.0,
 'Casco': 2.0,
 'Chebeague Island': 3.0,
 'Naples': 3.0,
 'Harrison': 4.0,
 'Frye Island': 3.0,
 'Buxton': 2.0,
 'Sabattus': 7.0,
 'Wiscasset': 3.0,
 'Newcastle': nan,
 'Hollis Center': 3.0,
 'New Gloucester': 3.0,
 'Gray': 3.0,
 'Poland': 4.0,
 'North Yarmouth': 4.0,
 'Farmingdale': 3.0,
 'Westport Island': 3.0,
 'Edgecomb': 3.0,
 'Dresden': 3.0,
 'Bowdoin': 3.0,
 'Kennebunkport': 4.0,
 'Norway': 2.0,
 'Porter': 1.0,
 'Mechanic Falls': 3.0,
 'Boothbay': 3.0,
 'Turner': 3.0,
 'Paris': 3.0,
 'Boothbay Harbor': 6.0,
 'Southport': 2.0,
 'Greene': 3.0,
 'Minot': 3.0,
 'West Paris': 3.0,
 'Sumner': 2.0,
 'Milton Township': 2.0,
 'Rumford': 4.0,
 'Mexico': 3.0,
 'Buckfield': 3.0,
 'Livermore Falls': 4.0,
 'Livermore': 3.0,
 'New Vineyard': 2.0,
 'Wayne': 3.0,
 'Dixfield': 3.0,
 'Fayette': 3.0,
 'Chesterville': 3.0,
 'Vienna': 1.0,
 'Industry': 2.0,
 'Carthage': 1.0,
 'Jay': 3.0,
 'Weld': 3.0,
 'Mount Vernon': 3.0,
 'Gilead': nan,
 'New Sharon': 4.0,
 'Rome': 3.0,
 'Readfield': 3.0,
 'Greenwood': nan,
 'Belgrade': 3.0,
 'Starks': 3.0,
 'Leeds': nan,
 'Otisfield': 3.0,
 'Byron': nan,
 'Sandy River Plt': 2.0,
 'Dallas Plt': 3.0,
 'Rangeley Plt': 3.0,
 'Oakland': 3.0,
 'Sidney': 3.0,
 'Coplin Plt': 3.0,
 'Phillips': 1.0,
 'Madrid Twp': 4.0,
 'Strong': 11.0,
 'Perkins Township': nan,
 'Skowhegan': 3.0,
 'Fairfield': 3.0,
 'Waterville': 5.0,
 'Winslow': 4.0,
 'Anson': 3.0,
 'Norridgewock': 3.0,
 'China': 3.0,
 'Nobleboro': 3.0,
 'South Bristol': 3.0,
 'Damariscotta': 3.0,
 'Vassalboro': 2.0,
 'Palermo': 1.0,
 'Liberty': 3.0,
 'Waldoboro': 3.0,
 'Appleton': 2.0,
 ...}

In [16]:
len(df1.city.unique())

2543